fix pre-push fail: husky and regexp

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,5 +1,4 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+#!/bin/bash
 
 echo -e "===\n>> Pre-push Hook: Checking branch name..."
 
@@ -8,7 +7,9 @@ PROTECTED_BRANCHES="^(master|develop|main)"
 
 if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
 then
-  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use Pull Request." && exit 1
+  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
 fi
 
-echo -e ">> Finish checking branch name\n==="
+echo -e ">> Finish checking branch name.\n==="
+
+exit 0
